### ISSUE TITLE
publish to Maven?

### ISSUE THREAD

**Issue by theburningmonk** [rpgreen/apigateway-generic-java-sdk#1]
hi, thanks for doing this work, it's exactly what I'm looking for after hours of searching for a simple way to make signed HTTP requests with Scala.

However, I couldn't find the package on maven central, any chance this can be published and shared as a maven package?

**Comment by eranation** [comment]
Looks like in progress, but might require to change the groupId 

See

https://issues.sonatype.org/browse/OSSRH-33417?focusedCommentId=423473&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-423473

**Comment by rpgreen** [comment]
Opened a new ticket @ https://issues.sonatype.org/browse/OSSRH-33644
Not sure who opened the original one

**Comment by eranation** [comment]
@rpgreen looks like it was approved! :)

**Comment by yakamoto69** [comment]
Is it released on Maven?

**Comment by jnawk** [comment]
bump

**Comment by rpgreen** [comment]
1.0 has been released on Maven central. You should be able to take a dependency on it with 
```
<dependency>
  <groupId>ca.ryangreen</groupId>
  <artifactId>apigateway-generic-java-sdk</artifactId>
  <version>1.0</version>
</dependency>
```

Let me know if any issues

**Comment by eranation** [comment]
Awesome, thanks! 
Can you please add a git tag on what was part of 1.0? just in case. thanks!
