### ISSUE TITLE
Client seems to swallow 404 errors 

### ISSUE THREAD

**Issue by eranation** [rpgreen/apigateway-generic-java-sdk#6]
I seem to get a JSON parsing error vs the http error code (e.g. for requesting a non existent URL)

**Comment by rpgreen** [comment]
Can you post the raw response from API Gateway and the specific error you are seeing?

Usually it's a 403 with 
```
{
"message": "Missing Authentication Token"
}
```

What would you expect the behavior to be in this case?

**Comment by eranation** [comment]
Will try and update soon

**Comment by eranation** [comment]
Didn't reproduce in a while, closing
